language: c
script:
  ./run-tests.sh
branches:
  only:
    - master
notifications:
  email:
    on_success: change # default: change (send a notification when the build status changes)
    on_failure: never # default: always
