language: c
addons:
  apt:
    packages:
      - freefem++
script:
  make tests
branches:
  only:
    - master
notifications:
  email:
    on_success: change # default: change (send a notification when the build status changes)
    on_failure: never # default: always
